#!/usr/bin/env bash

# ============================================================
# AUTOMATED EMMI ANALYSIS
#
# Usage:
#   ./automatic_irradiated_analysis.sh A1 T
#   ./automatic_irradiated_analysis.sh A1 v
#   ./automatic_irradiated_analysis.sh B2 T
#
# The script must be located inside the main "emmi" directory.
#
# Implemented phases:
#   PHASE 1 - before_annealing
#   PHASE 2 - all directories matching DATA_irradiated/annealing_*
#   PHASE 3 - global hotspot-ID assignment and merge across all phases
#
# Folder structure created inside every selected run:
#   1originals
#   2processed
#   3rotated
#   4coordinates
#   5th2f
#   6luminosity
#
# ============================================================

set -Eeuo pipefail
shopt -s nullglob

# ------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="$BASE_DIR/DATA_irradiated_NOisolated_changeR"

PROCESS_IMAGE="$BASE_DIR/manipulate_images/process_image.py"
TIF2TH2="$BASE_DIR/manipulate_images/tif2th2.py"

MEASURE_ROTATION="$BASE_DIR/tools_light_on/measure-rotation.py"
ROTATE_IMAGE="$BASE_DIR/tools_light_on/rotate-image.py"
MEASURE_SHIFT="$BASE_DIR/tools_light_on/measure-shift.py"
SHIFT_IMAGE="$BASE_DIR/tools_light_on/shift-image.py"

FIND_DEFECTS="$BASE_DIR/find_centers/find_defects_NOisolated_changeR.py"

SPOT_LUM_DIR="$BASE_DIR/spot_luminosity"
SPOT_LUM_MACRO="spot_luminosity_sum_irradiated.C"

PYTHON="${PYTHON:-python3}"

# Spatial tolerance used in PHASE 3 to identify the same hotspot
# in different annealing phases after geometrical alignment.
MATCH_RADIUS="${MATCH_RADIUS:-10.0}"
# Tolerance used to associate the coordinates written in 4coordinates
# and the luminosity rows produced by ROOT. These should normally agree
# to much better than one pixel.
COORD_MATCH_RADIUS="${COORD_MATCH_RADIUS:-1.0}"
MERGED_DIR="$DATA_DIR/merged_files"

# Breakdown voltages used only when T is constant and v_fin is calculated.
# A1 and B1 are the values already used in the previous analysis scripts.
#
# IMPORTANT:
# set A2/B2 here when their measured breakdown voltages are known.
VBD_A1="${VBD_A1:-51.3}"
VBD_A2="${VBD_A2:-}"
VBD_B1="${VBD_B1:-50.9}"
VBD_B2="${VBD_B2:-}"

# Global alignment table generated by PHASE 2.
ALIGNMENT_TABLE=""

# Rotated data=light image from before_annealing.
# This becomes the geometrical reference for all annealing phases.
BASE_LIGHT_REFERENCE=""

# ------------------------------------------------------------
# LOGGING / ERRORS
# ------------------------------------------------------------

log() {
    printf '\n[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

warn() {
    printf 'WARNING: %s\n' "$*" >&2
}

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

on_error() {
    local exit_code=$?
    local line_no=$1
    printf '\nERROR: pipeline stopped at line %s (exit code %s).\n' \
        "$line_no" "$exit_code" >&2
    exit "$exit_code"
}

trap 'on_error $LINENO' ERR

# ------------------------------------------------------------
# INPUT
# ------------------------------------------------------------

if [[ $# -ne 2 ]]; then
    cat >&2 <<EOF
Usage:
  $0 SENSOR CONSTANT

SENSOR:
  A1 | A2 | B1 | B2

CONSTANT:
  T | v

Examples:
  $0 A1 T
  $0 B1 v
EOF
    exit 1
fi

SENSOR="$1"
CONSTANT="$2"

case "$SENSOR" in
    A1|A2|B1|B2) ;;
    *) die "Invalid sensor '$SENSOR'. Allowed values: A1 A2 B1 B2." ;;
esac

case "$CONSTANT" in
    T|v) ;;
    *) die "Invalid constant '$CONSTANT'. Allowed values: T or v." ;;
esac

[[ -d "$DATA_DIR" ]] || die "DATA directory not found: $DATA_DIR"

# ------------------------------------------------------------
# CHECK REQUIRED PROGRAMS / FILES
# ------------------------------------------------------------

check_requirements() {
    command -v "$PYTHON" >/dev/null 2>&1 \
        || die "Python executable not found: $PYTHON"

    command -v root >/dev/null 2>&1 \
        || die "ROOT executable 'root' not found in PATH."

    local required_files=(
        "$PROCESS_IMAGE"
        "$TIF2TH2"
        "$MEASURE_ROTATION"
        "$ROTATE_IMAGE"
        "$MEASURE_SHIFT"
        "$SHIFT_IMAGE"
        "$FIND_DEFECTS"
        "$SPOT_LUM_DIR/$SPOT_LUM_MACRO"
    )

    local f
    for f in "${required_files[@]}"; do
        [[ -f "$f" ]] || die "Required file not found: $f"
    done
}

# ------------------------------------------------------------
# SENSOR CONFIGURATION
# ------------------------------------------------------------

get_vbd() {
    case "$SENSOR" in
        A1) printf '%s\n' "$VBD_A1" ;;
        A2) printf '%s\n' "$VBD_A2" ;;
        B1) printf '%s\n' "$VBD_B1" ;;
        B2) printf '%s\n' "$VBD_B2" ;;
    esac
}

# ------------------------------------------------------------
# FILENAME / DIRECTORY HELPERS
# ------------------------------------------------------------

extract_run_number() {
    local run_dir="$1"
    local name
    name="$(basename "$run_dir")"

    if [[ "$name" =~ _run=(.+)$ ]]; then
        printf '%s\n' "${BASH_REMATCH[1]}"
    else
        die "Cannot extract run number from directory: $run_dir"
    fi
}

extract_run_prefix() {
    local run_dir="$1"
    local name
    name="$(basename "$run_dir")"

    if [[ "$name" =~ ^(.+)_run=.+$ ]]; then
        printf '%s\n' "${BASH_REMATCH[1]}"
    else
        die "Cannot extract run prefix from directory: $run_dir"
    fi
}

find_selected_run_dir() {
    local phase_dir="$1"
    local pattern="${SENSOR}_${CONSTANT}=*_run=*"

    local matches=()
    while IFS= read -r -d '' d; do
        matches+=("$d")
    done < <(
        find "$phase_dir" \
            -mindepth 1 -maxdepth 1 \
            -type d \
            -name "$pattern" \
            -print0
    )

    if (( ${#matches[@]} == 0 )); then
        return 1
    fi

    if (( ${#matches[@]} > 1 )); then
        printf 'ERROR: more than one directory matches %s in %s:\n' \
            "$pattern" "$phase_dir" >&2
        printf '  %s\n' "${matches[@]}" >&2
        die "The selected sensor/constant must identify exactly one run per phase."
    fi

    printf '%s\n' "${matches[0]}"
}

strip_tif_extension() {
    local name="$1"
    name="${name%.tif}"
    name="${name%.TIF}"
    name="${name%.tiff}"
    name="${name%.TIFF}"
    printf '%s\n' "$name"
}

# Extract T or v from an EMMI filename.
extract_parameter() {
    local filename="$1"
    local parameter="$2"

    "$PYTHON" - "$filename" "$parameter" <<'PY'
import os
import re
import sys

name = os.path.basename(sys.argv[1])
parameter = sys.argv[2]

m = re.search(
    rf'(?:^|_){re.escape(parameter)}=([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)',
    name
)

if m is None:
    raise SystemExit(
        f"Cannot extract parameter {parameter!r} from filename: {name}"
    )

print(m.group(1))
PY
}

# ------------------------------------------------------------
# RUN DIRECTORY RESET
# ------------------------------------------------------------

prepare_run_output_dirs() {
    local run_dir="$1"

    local dirs=(
        "$run_dir/2processed"
        "$run_dir/3rotated"
        "$run_dir/4coordinates"
        "$run_dir/5th2f"
        "$run_dir/6luminosity"
    )

    log "Preparing output directories for run: $(basename "$run_dir")"

    local d
    for d in "${dirs[@]}"; do
        rm -rf "$d"
        mkdir -p "$d"
    done
}

# ------------------------------------------------------------
# PHASE STEP 1 - IMAGE CLEANUP
# ------------------------------------------------------------

cleanup_images() {
    local run_dir="$1"

    local originals_dir="$run_dir/1originals"
    local processed_dir="$run_dir/2processed"

    [[ -d "$originals_dir" ]] \
        || die "Missing input directory: $originals_dir"

    mkdir -p "$processed_dir"

    log "1/5 - Image cleanup: $(basename "$run_dir")"

    local n_files=0
    local input_file filename stem output_file

    while IFS= read -r -d '' input_file; do
        filename="$(basename "$input_file")"
        stem="$(strip_tif_extension "$filename")"
        output_file="$processed_dir/${stem}_processed.tif"

        "$PYTHON" "$PROCESS_IMAGE" \
            --input "$input_file" \
            --process remove_column_bias remove_hot_pixels remove_cold_pixels \
            --output "$output_file"

        ((n_files += 1))
    done < <(
        find "$originals_dir" \
            -maxdepth 1 \
            -type f \
            \( -iname '*.tif' -o -iname '*.tiff' \) \
            -print0
    )

    (( n_files > 0 )) \
        || die "No TIF files found in $originals_dir"
}

# ------------------------------------------------------------
# ROTATION HELPERS
# ------------------------------------------------------------

get_unique_light_image() {
    local directory="$1"

    local matches=()
    local f

    while IFS= read -r -d '' f; do
        matches+=("$f")
    done < <(
        find "$directory" \
            -maxdepth 1 \
            -type f \
            \( -iname '*.tif' -o -iname '*.tiff' \) \
            -name '*data=light*' \
            -print0
    )

    (( ${#matches[@]} > 0 )) \
        || die "No data=light TIF image found in $directory"

    (( ${#matches[@]} == 1 )) \
        || die "More than one data=light image found in $directory"

    printf '%s\n' "${matches[0]}"
}

measure_rotation_angle() {
    local light_image="$1"
    local output angle

    output="$(
        "$PYTHON" "$MEASURE_ROTATION" --input "$light_image"
    )"

    printf '%s\n' "$output" >&2

    angle="$(
        printf '%s\n' "$output" |
        "$PYTHON" -c '
import re
import sys

text = sys.stdin.read()
m = re.search(
    r"rotation angle:\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)",
    text
)

if m is None:
    raise SystemExit("Cannot parse rotation angle from measure-rotation.py output.")

print(m.group(1))
'
    )"

    printf '%s\n' "$angle"
}

# clipy/clipx are defined here as the symmetric number of pixels removed
# PER SIDE by rotate-image.py, inferred from the actual input/output shapes.
# If rotate-image.py preserves the input dimensions, both values are zero.
measure_rotation_clip() {
    local input_image="$1"
    local rotated_image="$2"

    "$PYTHON" - "$input_image" "$rotated_image" <<'PY'
import sys
import tifffile

before = tifffile.imread(sys.argv[1])
after = tifffile.imread(sys.argv[2])

if before.ndim < 2 or after.ndim < 2:
    raise SystemExit("Rotation clipping check requires at least 2D images.")

ny0, nx0 = before.shape[-2:]
ny1, nx1 = after.shape[-2:]

dy = ny0 - ny1
dx = nx0 - nx1

if dy < 0 or dx < 0:
    # The rotation enlarged the canvas instead of clipping it.
    # For the requested metadata, no pixels were removed.
    clipy = 0.0
    clipx = 0.0
else:
    clipy = dy / 2.0
    clipx = dx / 2.0

print(f"{clipy:g} {clipx:g}")
PY
}

rotate_all_processed_images() {
    local processed_dir="$1"
    local destination_dir="$2"
    local angle="$3"

    mkdir -p "$destination_dir"

    local input_file filename stem output_file

    while IFS= read -r -d '' input_file; do
        filename="$(basename "$input_file")"
        stem="$(strip_tif_extension "$filename")"
        output_file="$destination_dir/${stem}_rotated.tif"

        "$PYTHON" "$ROTATE_IMAGE" \
            --input "$input_file" \
            --angle "$angle" \
            --output "$output_file"
    done < <(
        find "$processed_dir" \
            -maxdepth 1 \
            -type f \
            -name '*_processed.tif' \
            -print0
    )
}

# ------------------------------------------------------------
# SHIFT HELPERS
# ------------------------------------------------------------

assert_same_image_shape() {
    local reference="$1"
    local moving="$2"

    "$PYTHON" - "$reference" "$moving" <<'PY'
import sys
import tifffile

ref = tifffile.imread(sys.argv[1])
mov = tifffile.imread(sys.argv[2])

if ref.shape != mov.shape:
    raise SystemExit(
        "Reference and moving light images have different shapes after rotation:\n"
        f"  reference: {ref.shape}\n"
        f"  moving:    {mov.shape}\n"
        "measure-shift.py should only be run on geometrically compatible images."
    )
PY
}

measure_shift_values() {
    local reference="$1"
    local moving="$2"
    local output

    output="$(
        "$PYTHON" "$MEASURE_SHIFT" \
            --input "$reference" "$moving"
    )"

    printf '%s\n' "$output" >&2

    printf '%s\n' "$output" |
    "$PYTHON" -c '
import re
import sys

text = sys.stdin.read()

number = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"

m = re.search(
    rf"detected subpixel offset\s*\(y,\s*x\)\s*:\s*"
    rf"\[\s*({number})[\s,]+({number})\s*\]",
    text
)

if m is None:
    raise SystemExit("Cannot parse shift from measure-shift.py output.")

print(m.group(1), m.group(2))
'
}

shift_all_rotated_images() {
    local source_dir="$1"
    local final_dir="$2"
    local shifty="$3"
    local shiftx="$4"

    mkdir -p "$final_dir"

    local input_file filename output_file

    while IFS= read -r -d '' input_file; do
        filename="$(basename "$input_file")"
        output_file="$final_dir/$filename"

        "$PYTHON" "$SHIFT_IMAGE" \
            --input "$input_file" \
            --shift "$shifty" "$shiftx" \
            --output "$output_file"
    done < <(
        find "$source_dir" \
            -maxdepth 1 \
            -type f \
            -name '*_rotated.tif' \
            -print0
    )
}

# ------------------------------------------------------------
# PHASE STEP 3 - REFERENCE COORDINATES
# ------------------------------------------------------------

select_second_highest_reference() {
    local rotated_dir="$1"

    local varying_parameter
    if [[ "$CONSTANT" == "T" ]]; then
        varying_parameter="v"
    else
        varying_parameter="T"
    fi

    "$PYTHON" - "$rotated_dir" "$varying_parameter" <<'PY'
from pathlib import Path
import re
import sys

directory = Path(sys.argv[1])
parameter = sys.argv[2]

# Only the differential emission images are candidates.
files = sorted(directory.glob("*data=diff*_processed_rotated.tif"))

# Exclude data=diffe explicitly, because "data=diffe" also contains "data=diff".
files = [f for f in files if "data=diffe" not in f.name]

pattern = re.compile(
    rf"(?:^|_){re.escape(parameter)}="
    rf"([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)"
)

entries = []
for f in files:
    m = pattern.search(f.name)
    if m:
        entries.append((float(m.group(1)), f))

if not entries:
    raise SystemExit(
        f"No data=diff images with parameter {parameter}=... found in {directory}"
    )

distinct_values = sorted({value for value, _ in entries}, reverse=True)

if len(distinct_values) < 2:
    raise SystemExit(
        f"Cannot select the second-highest {parameter}: "
        f"only {len(distinct_values)} distinct value(s) found in {directory}."
    )

target = distinct_values[1]
matches = [f for value, f in entries if value == target]

if len(matches) != 1:
    raise SystemExit(
        f"Expected exactly one reference image at second-highest "
        f"{parameter}={target}, found {len(matches)}."
    )

print(matches[0])
PY
}

generate_reference_coordinates() {
    local run_dir="$1"
    local phase="$2"
    local run_number="$3"
    local run_prefix="$4"

    local rotated_dir="$run_dir/3rotated"
    local coordinates_dir="$run_dir/4coordinates"

    mkdir -p "$coordinates_dir"

    log "3/5 - Reference coordinates: $phase / run=$run_number" >&2

    local ref_image
    ref_image="$(select_second_highest_reference "$rotated_dir")"

    local reference_coords
    reference_coords="$coordinates_dir/${run_prefix}_${phase}_run=${run_number}_reference_coordinates.txt"

    # Redirect the diagnostic stdout of the source-finding program to stderr:
    # this function itself prints ONLY the coordinate-file path on stdout,
    # because its caller captures that value with command substitution.
    "$PYTHON" "$FIND_DEFECTS" \
        --input "$ref_image" \
        --coordinates_root "$reference_coords" >&2

    [[ -s "$reference_coords" ]] \
        || die "Reference coordinate file was not created or is empty: $reference_coords"

    printf '%s\n' "$reference_coords"
}

# ------------------------------------------------------------
# PHASE STEP 4 - TIF -> TH2F
# ------------------------------------------------------------

convert_to_th2f() {
    local run_dir="$1"

    local rotated_dir="$run_dir/3rotated"
    local root_dir="$run_dir/5th2f"

    mkdir -p "$root_dir"

    log "4/5 - TIF to TH2F conversion: $(basename "$run_dir")"

    local input_file error_file filename stem output_file
    local n_converted=0

    while IFS= read -r -d '' input_file; do

        # Skip the uncertainty image itself.
        [[ "$input_file" == *"data=diffe"* ]] && continue

        error_file="${input_file/data=diff/data=diffe}"

        [[ -f "$error_file" ]] || die \
            "Missing matching data=diffe image for:\n  $input_file\nExpected:\n  $error_file"

        filename="$(basename "$input_file")"
        stem="$(strip_tif_extension "$filename")"
        output_file="$root_dir/${stem}_th2f.root"

        "$PYTHON" "$TIF2TH2" \
            --input "$input_file" \
            --error "$error_file" \
            --output "$output_file"

        ((n_converted += 1))

    done < <(
        find "$rotated_dir" \
            -maxdepth 1 \
            -type f \
            -name '*data=diff*_processed_rotated.tif' \
            -print0
    )

    (( n_converted > 0 )) \
        || die "No differential images converted in $rotated_dir"
}

# ------------------------------------------------------------
# PHASE STEP 5 - LUMINOSITY
# ------------------------------------------------------------

calculate_luminosity() {
    local run_dir="$1"
    local phase="$2"
    local run_number="$3"
    local run_prefix="$4"
    local reference_coords="$5"

    local root_dir="$run_dir/5th2f"
    local lum_dir="$run_dir/6luminosity"

    mkdir -p "$lum_dir"

    # Remove only intermediate CSV files generated by this pipeline,
    # so that stale files from an older execution are not merged.
    rm -f "$lum_dir"/luminosity_*_processed_rotated.csv

    log "5/5 - Luminosity calculation: $phase / run=$run_number"

    local root_file filename stem val_T val_v out_csv

    while IFS= read -r -d '' root_file; do
        filename="$(basename "$root_file")"
        stem="${filename%_th2f.root}"

        val_T="$(extract_parameter "$filename" "T")"
        val_v="$(extract_parameter "$filename" "v")"

        (
            cd "$SPOT_LUM_DIR"

            rm -f luminosity_results.csv

            root -l -q \
                "${SPOT_LUM_MACRO}(\"${root_file}\",\"${reference_coords}\")"

            [[ -f luminosity_results.csv ]] \
                || die "ROOT macro did not create luminosity_results.csv for $root_file"

            out_csv="$lum_dir/luminosity_${stem}.csv"

            awk -v t="$val_T" -v v="$val_v" '
                BEGIN {
                    FS=","
                    OFS=","
                }
                {
                    gsub(/[[:space:]]+$/, "", $0)

                    if ($0 != "") {
                        if (NR == 1)
                            print $0, "T", "v"
                        else
                            print $0, t, v
                    }
                }
            ' luminosity_results.csv > "$out_csv"

            rm -f luminosity_results.csv
        )

    done < <(
        find "$root_dir" \
            -maxdepth 1 \
            -type f \
            -name '*data=diff*_processed_rotated_th2f.root' \
            -print0
    )

    merge_luminosity_csvs \
        "$lum_dir" \
        "$phase" \
        "$run_number" \
        "$run_prefix"
}

merge_luminosity_csvs() {
    local lum_dir="$1"
    local phase="$2"
    local run_number="$3"
    local run_prefix="$4"

    local vbd
    vbd="$(get_vbd)"

    local output_name="${run_prefix}_${phase}_run=${run_number}.csv"
    local output_path="$lum_dir/$output_name"

    log "Merging luminosity CSVs -> $output_name"

    SENSOR_ENV="$SENSOR" \
    CONSTANT_ENV="$CONSTANT" \
    VBD_ENV="$vbd" \
    LUM_DIR_ENV="$lum_dir" \
    OUTPUT_PATH_ENV="$output_path" \
    "$PYTHON" <<'PY'
import glob
import os
import sys
import pandas as pd

sensor = os.environ["SENSOR_ENV"]
constant = os.environ["CONSTANT_ENV"]
vbd_text = os.environ.get("VBD_ENV", "")
lum_dir = os.environ["LUM_DIR_ENV"]
output_path = os.environ["OUTPUT_PATH_ENV"]

files = sorted(
    glob.glob(os.path.join(lum_dir, "luminosity_*_processed_rotated.csv"))
)

if not files:
    raise SystemExit(f"No luminosity intermediate CSV files found in {lum_dir}")

frames = []
for path in files:
    df = pd.read_csv(path)
    frames.append(df)

full_df = pd.concat(frames, ignore_index=True)

required = {"x", "y", "T", "v"}
missing = required.difference(full_df.columns)
if missing:
    raise SystemExit(
        "Missing required columns in luminosity CSV files: "
        + ", ".join(sorted(missing))
    )

# The ROOT macro is called with one common coordinate file for all
# operating conditions in this run, so identical x,y identify the same spot.
full_df["spot"] = full_df.groupby(["x", "y"], sort=True).ngroup()

columns = ["spot"] + [c for c in full_df.columns if c != "spot"]
full_df = full_df[columns]

full_df["T"] = pd.to_numeric(full_df["T"], errors="raise")
full_df["v"] = pd.to_numeric(full_df["v"], errors="raise")

if constant == "T":
    # T fixed -> v changes.
    # Keep absolute v and, when VBD is configured, add v_fin.
    if vbd_text.strip():
        vbd = float(vbd_text)
        full_df["v_fin"] = full_df["v"] - vbd
    else:
        # Do not invent a breakdown voltage.
        full_df["v_fin"] = float("nan")
        print(
            f"WARNING: VBD for {sensor} is not configured. "
            "Column v_fin is written as NaN; absolute v is preserved.",
            file=sys.stderr,
        )

    full_df = full_df.sort_values(
        by=["spot", "v"],
        kind="stable",
    )

else:
    # v fixed -> T changes.
    full_df = full_df.sort_values(
        by=["spot", "T"],
        kind="stable",
    )

full_df.to_csv(output_path, index=False)

print(f"Final merged file created: {output_path}")
PY

    [[ -s "$output_path" ]] \
        || die "Merged luminosity file not created: $output_path"
}

# ------------------------------------------------------------
# PHASE 1 - BEFORE ANNEALING
# ------------------------------------------------------------

process_before_annealing() {
    local phase="before_annealing"
    local phase_dir="$DATA_DIR/$phase"

    [[ -d "$phase_dir" ]] \
        || die "Missing required phase directory: $phase_dir"

    local run_dir
    run_dir="$(find_selected_run_dir "$phase_dir")" \
        || die "No run found for ${SENSOR}_${CONSTANT}=* in $phase_dir"

    local run_number run_prefix
    run_number="$(extract_run_number "$run_dir")"
    run_prefix="$(extract_run_prefix "$run_dir")"

    local processed_dir="$run_dir/2processed"
    local rotated_dir="$run_dir/3rotated"

    printf '\n'
    printf '============================================================\n'
    printf 'PHASE 1 - BEFORE ANNEALING\n'
    printf 'Sensor:   %s\n' "$SENSOR"
    printf 'Constant: %s\n' "$CONSTANT"
    printf 'Run:      %s\n' "$run_number"
    printf 'Folder:   %s\n' "$run_dir"
    printf '============================================================\n'

    # Prepare the run from a clean state and recreate all output directories
    prepare_run_output_dirs "$run_dir"

    # 1. cleanup
    cleanup_images "$run_dir"

    # 2. rotation
    log "2/5 - Image rotation: before_annealing"

    local light_processed
    light_processed="$(get_unique_light_image "$processed_dir")"

    local angle
    angle="$(measure_rotation_angle "$light_processed")"

    rotate_all_processed_images \
        "$processed_dir" \
        "$rotated_dir" \
        "$angle"

    local light_name light_stem
    light_name="$(basename "$light_processed")"
    light_stem="$(strip_tif_extension "$light_name")"

    BASE_LIGHT_REFERENCE="$rotated_dir/${light_stem}_rotated.tif"

    [[ -f "$BASE_LIGHT_REFERENCE" ]] \
        || die "Rotated before_annealing light reference not found: $BASE_LIGHT_REFERENCE"

    local clipy clipx
    read -r clipy clipx < <(
        measure_rotation_clip \
            "$light_processed" \
            "$BASE_LIGHT_REFERENCE"
    )

    printf 'Before-annealing geometrical reference:\n'
    printf '  angle = %s deg\n' "$angle"
    printf '  clipy = %s px/side\n' "$clipy"
    printf '  clipx = %s px/side\n' "$clipx"
    printf '  light = %s\n' "$BASE_LIGHT_REFERENCE"

    # 3. coordinates
    local reference_coords
    reference_coords="$(
        generate_reference_coordinates \
            "$run_dir" \
            "$phase" \
            "$run_number" \
            "$run_prefix"
    )"

    # 4. TH2F
    convert_to_th2f "$run_dir"

    # 5. luminosity
    calculate_luminosity \
        "$run_dir" \
        "$phase" \
        "$run_number" \
        "$run_prefix" \
        "$reference_coords"
}

# ------------------------------------------------------------
# PHASE 2 - ANNEALING PHASES
# ------------------------------------------------------------

process_one_annealing_phase() {
    local phase_dir="$1"
    local phase
    phase="$(basename "$phase_dir")"

    local run_dir
    if ! run_dir="$(find_selected_run_dir "$phase_dir")"; then
        warn "Skipping $phase: no ${SENSOR}_${CONSTANT}=*_run=* directory found."
        return 0
    fi

    local run_number run_prefix
    run_number="$(extract_run_number "$run_dir")"
    run_prefix="$(extract_run_prefix "$run_dir")"

    local processed_dir="$run_dir/2processed"
    local rotated_dir="$run_dir/3rotated"

    # Temporary directory: contains rotation-only images.
    # Final shifted images are written directly in 3rotated.
    local prealign_dir="$run_dir/.3rotated_pre_shift"

    rm -rf "$prealign_dir"
    mkdir -p "$prealign_dir" "$rotated_dir"

    printf '\n'
    printf '============================================================\n'
    printf 'PHASE 2 - %s\n' "$phase"
    printf 'Sensor:   %s\n' "$SENSOR"
    printf 'Constant: %s\n' "$CONSTANT"
    printf 'Run:      %s\n' "$run_number"
    printf 'Folder:   %s\n' "$run_dir"
    printf '============================================================\n'

    # Prepare the run from a clean state and recreate all output directories
    prepare_run_output_dirs "$run_dir"

    # 1. cleanup
    cleanup_images "$run_dir"

    # 2a/2b. measure rotation from light image
    log "2/5 - Rotation + alignment: $phase"

    local light_processed
    light_processed="$(get_unique_light_image "$processed_dir")"

    local angle
    angle="$(measure_rotation_angle "$light_processed")"

    # 2c. rotate ALL processed TIF images
    rotate_all_processed_images \
        "$processed_dir" \
        "$prealign_dir" \
        "$angle"

    local light_name light_stem moving_light
    light_name="$(basename "$light_processed")"
    light_stem="$(strip_tif_extension "$light_name")"
    moving_light="$prealign_dir/${light_stem}_rotated.tif"

    [[ -f "$moving_light" ]] \
        || die "Rotated moving light image not found: $moving_light"

    local clipy clipx
    read -r clipy clipx < <(
        measure_rotation_clip \
            "$light_processed" \
            "$moving_light"
    )

    # 2d. measure shift with respect to before_annealing reference
    [[ -n "$BASE_LIGHT_REFERENCE" && -f "$BASE_LIGHT_REFERENCE" ]] \
        || die "Before-annealing light reference is not available."

    assert_same_image_shape \
        "$BASE_LIGHT_REFERENCE" \
        "$moving_light"

    local shifty shiftx
    read -r shifty shiftx < <(
        measure_shift_values \
            "$BASE_LIGHT_REFERENCE" \
            "$moving_light"
    )

    printf 'Alignment parameters:\n'
    printf '  phase  = %s\n' "$phase"
    printf '  run    = %s\n' "$run_number"
    printf '  angle  = %s deg\n' "$angle"
    printf '  clipy  = %s px/side\n' "$clipy"
    printf '  clipx  = %s px/side\n' "$clipx"
    printf '  shifty = %s px\n' "$shifty"
    printf '  shiftx = %s px\n' "$shiftx"

    # Apply the same measured translation to ALL images in this run.
    shift_all_rotated_images \
        "$prealign_dir" \
        "$rotated_dir" \
        "$shifty" \
        "$shiftx"

    rm -rf "$prealign_dir"

    # Alignment metadata requested for every annealing phase.
    printf '%s,%s,%s,%s,%s,%s,%s\n' \
        "$phase" \
        "$run_number" \
        "$angle" \
        "$clipy" \
        "$clipx" \
        "$shifty" \
        "$shiftx" \
        >> "$ALIGNMENT_TABLE"

    # 3. coordinates on the FINAL aligned images
    local reference_coords
    reference_coords="$(
        generate_reference_coordinates \
            "$run_dir" \
            "$phase" \
            "$run_number" \
            "$run_prefix"
    )"

    # 4. TH2F from FINAL aligned images
    convert_to_th2f "$run_dir"

    # 5. luminosity
    calculate_luminosity \
        "$run_dir" \
        "$phase" \
        "$run_number" \
        "$run_prefix" \
        "$reference_coords"
}

process_annealing_phases() {
    ALIGNMENT_TABLE="$DATA_DIR/alignment_${SENSOR}_${CONSTANT}.csv"

    printf '%s\n' \
        "annealing_phase,run_number,angle,clipy,clipx,shifty,shiftx" \
        > "$ALIGNMENT_TABLE"

    local phase_dirs=()

    while IFS= read -r d; do
        phase_dirs+=("$d")
    done < <(
        find "$DATA_DIR" \
            -mindepth 1 -maxdepth 1 \
            -type d \
            -name 'annealing_*' \
            -print |
        sort -V
    )

    if (( ${#phase_dirs[@]} == 0 )); then
        warn "No annealing_* directories found in $DATA_DIR"
        return 0
    fi

    local phase_dir
    for phase_dir in "${phase_dirs[@]}"; do
        process_one_annealing_phase "$phase_dir"
    done

    log "Alignment table created: $ALIGNMENT_TABLE"
}

# ------------------------------------------------------------
# PHASE 3 - GLOBAL HOTSPOT IDS + FORCED LUMINOSITY MEASUREMENT
# ------------------------------------------------------------

merge_all_phases_global_ids() {
    mkdir -p "$MERGED_DIR"

    local vbd
    vbd="$(get_vbd)"

    printf '\n'
    printf '============================================================\n'
    printf 'PHASE 3 - GLOBAL HOTSPOT MATCHING + FORCED MEASUREMENT\n'
    printf 'Sensor:             %s\n' "$SENSOR"
    printf 'Constant:           %s\n' "$CONSTANT"
    printf 'Match radius:       %s px\n' "$MATCH_RADIUS"
    printf 'Coordinate tolerance: %s px\n' "$COORD_MATCH_RADIUS"
    printf 'Output:             %s\n' "$MERGED_DIR"
    printf '============================================================\n'

    SENSOR_ENV="$SENSOR" \
    CONSTANT_ENV="$CONSTANT" \
    MATCH_RADIUS_ENV="$MATCH_RADIUS" \
    COORD_MATCH_RADIUS_ENV="$COORD_MATCH_RADIUS" \
    DATA_DIR_ENV="$DATA_DIR" \
    MERGED_DIR_ENV="$MERGED_DIR" \
    SPOT_LUM_DIR_ENV="$SPOT_LUM_DIR" \
    SPOT_LUM_MACRO_ENV="$SPOT_LUM_MACRO" \
    VBD_ENV="$vbd" \
    "$PYTHON" <<'PY_PHASE3'
from pathlib import Path
import math
import os
import re
import subprocess
import sys

import numpy as np
import pandas as pd

sensor = os.environ["SENSOR_ENV"]
constant = os.environ["CONSTANT_ENV"]
match_radius = float(os.environ["MATCH_RADIUS_ENV"])
coord_match_radius = float(os.environ["COORD_MATCH_RADIUS_ENV"])
data_dir = Path(os.environ["DATA_DIR_ENV"])
merged_root = Path(os.environ["MERGED_DIR_ENV"])
spot_lum_dir = Path(os.environ["SPOT_LUM_DIR_ENV"])
spot_lum_macro = os.environ["SPOT_LUM_MACRO_ENV"]
vbd_text = os.environ.get("VBD_ENV", "").strip()
merged_root.mkdir(parents=True, exist_ok=True)

required_columns = ["spot", "x", "y", "luminosity", "error", "T", "v"]


# ============================================================
# GENERIC HELPERS
# ============================================================

def phase_sort_key(phase: str):
    if phase == "before_annealing":
        return (0, -math.inf, -math.inf, phase)

    m = re.fullmatch(
        r"annealing_T=([-+]?(?:\d+(?:\.\d*)?|\.\d+))_h="
        r"([-+]?(?:\d+(?:\.\d*)?|\.\d+))",
        phase,
    )
    if m:
        return (1, float(m.group(1)), float(m.group(2)), phase)

    return (2, math.inf, math.inf, phase)


def extract_parameter_from_name(filename: str, parameter: str) -> float:
    m = re.search(
        rf"(?:^|_){re.escape(parameter)}="
        rf"([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)",
        filename,
    )
    if m is None:
        raise ValueError(
            f"Cannot extract parameter {parameter!r} from filename: {filename}"
        )
    return float(m.group(1))


def check_columns(df: pd.DataFrame, path: Path):
    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        raise ValueError(
            f"File {path} is missing required columns: {missing}. "
            f"Found columns: {list(df.columns)}"
        )


def mean_coordinates_per_local_spot(df: pd.DataFrame) -> pd.DataFrame:
    tmp = df.copy()
    tmp["x"] = pd.to_numeric(tmp["x"], errors="raise")
    tmp["y"] = pd.to_numeric(tmp["y"], errors="raise")

    return (
        tmp.groupby("spot", as_index=False, sort=True)
        .agg(x_mean=("x", "mean"), y_mean=("y", "mean"))
    )


def greedy_one_to_one(source_rows, target_rows, source_id, target_id,
                      sx, sy, tx, ty, radius):
    """Return one-to-one nearest-neighbour mapping within radius."""
    pairs = []
    candidate_counts = {}

    for _, src in source_rows.iterrows():
        sid = src[source_id]
        n_candidates = 0

        for _, tgt in target_rows.iterrows():
            tid = tgt[target_id]
            distance = math.hypot(
                float(src[sx]) - float(tgt[tx]),
                float(src[sy]) - float(tgt[ty]),
            )
            if distance <= radius:
                pairs.append((distance, sid, tid))
                n_candidates += 1

        candidate_counts[sid] = n_candidates

    pairs.sort(key=lambda item: item[0])

    assigned_source = set()
    assigned_target = set()
    mapping = {}
    distances = {}

    for distance, sid, tid in pairs:
        if sid in assigned_source or tid in assigned_target:
            continue
        mapping[sid] = tid
        distances[sid] = distance
        assigned_source.add(sid)
        assigned_target.add(tid)

    return mapping, distances, candidate_counts


# ============================================================
# DISCOVER INPUT DATASETS
# ============================================================

def find_dataset_csvs():
    phase_dirs = [
        p for p in data_dir.iterdir()
        if p.is_dir()
        and (p.name == "before_annealing" or p.name.startswith("annealing_"))
    ]
    phase_dirs.sort(key=lambda p: phase_sort_key(p.name))

    datasets = []
    run_pattern = re.compile(
        rf"^{re.escape(sensor)}_{re.escape(constant)}=(.+)_run=(.+)$"
    )

    for phase_dir in phase_dirs:
        matching_runs = [
            p for p in phase_dir.iterdir()
            if p.is_dir() and run_pattern.fullmatch(p.name)
        ]

        if not matching_runs:
            continue

        if len(matching_runs) > 1:
            raise RuntimeError(
                f"More than one run matches {sensor}_{constant}=*_run=* "
                f"inside {phase_dir}:\n  "
                + "\n  ".join(str(p) for p in matching_runs)
            )

        run_dir = matching_runs[0]
        m = run_pattern.fullmatch(run_dir.name)
        assert m is not None

        fixed_value = m.group(1)
        run_number = m.group(2)
        run_prefix = f"{sensor}_{constant}={fixed_value}"
        phase = phase_dir.name

        csv_path = (
            run_dir
            / "6luminosity"
            / f"{run_prefix}_{phase}_run={run_number}.csv"
        )

        if not csv_path.is_file():
            raise FileNotFoundError(
                "Final luminosity CSV expected from phases 1/2 was not found:\n"
                f"  {csv_path}"
            )

        coord_dir = run_dir / "4coordinates"
        coord_files = sorted(coord_dir.glob("*_reference_coordinates.txt"))
        if len(coord_files) != 1:
            raise RuntimeError(
                f"Expected exactly one reference coordinate file in {coord_dir}; "
                f"found {len(coord_files)}."
            )

        root_dir = run_dir / "5th2f"
        root_files = sorted(
            p for p in root_dir.glob("*data=diff*_processed_rotated_th2f.root")
            if "data=diffe" not in p.name
        )
        if not root_files:
            raise RuntimeError(f"No TH2F data=diff files found in {root_dir}")

        datasets.append({
            "phase": phase,
            "phase_order": len(datasets),
            "run_dir": run_dir,
            "run_number": run_number,
            "run_prefix": run_prefix,
            "fixed_value": fixed_value,
            "path": csv_path,
            "coord_path": coord_files[0],
            "root_files": root_files,
        })

    if not datasets:
        raise RuntimeError(
            f"No merged luminosity CSV found for sensor={sensor}, "
            f"constant={constant}."
        )

    if datasets[0]["phase"] != "before_annealing":
        raise RuntimeError(
            "before_annealing is required as the global-ID reference."
        )

    return datasets


def read_reference_coordinates(path: Path) -> pd.DataFrame:
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw in enumerate(handle, start=1):
            line = raw.strip()
            if not line:
                continue

            fields = [part.strip() for part in line.split(",")]
            if len(fields) < 4:
                raise ValueError(
                    f"Invalid coordinate line {line_number} in {path}: {raw.rstrip()}"
                )

            try:
                x, y, area, radius = map(float, fields[:4])
            except ValueError as exc:
                raise ValueError(
                    f"Non-numeric coordinate line {line_number} in {path}: "
                    f"{raw.rstrip()}"
                ) from exc

            rows.append({
                "coord_index": len(rows),
                "x_coord": x,
                "y_coord": y,
                "integration_area": area,
                "integration_radius": radius,
            })

    if not rows:
        raise RuntimeError(f"Coordinate file is empty: {path}")

    return pd.DataFrame(rows)


def attach_local_geometry(local_spots: pd.DataFrame, coordinates: pd.DataFrame,
                          phase: str):
    mapping, distances, candidate_counts = greedy_one_to_one(
        source_rows=local_spots,
        target_rows=coordinates,
        source_id="spot",
        target_id="coord_index",
        sx="x_mean",
        sy="y_mean",
        tx="x_coord",
        ty="y_coord",
        radius=coord_match_radius,
    )

    missing = [spot for spot in local_spots["spot"] if spot not in mapping]
    if missing:
        raise RuntimeError(
            f"Could not associate local spots with the 4coordinates file in "
            f"phase={phase}. Missing local spot IDs: {missing}. "
            f"Increase COORD_MATCH_RADIUS only if the coordinate systems are known "
            f"to differ slightly."
        )

    coord_lookup = coordinates.set_index("coord_index")
    geometry = {}

    for local_spot, coord_index in mapping.items():
        row = coord_lookup.loc[coord_index]
        geometry[local_spot] = {
            "x": float(row["x_coord"]),
            "y": float(row["y_coord"]),
            "integration_area": float(row["integration_area"]),
            "integration_radius": float(row["integration_radius"]),
            "coordinate_match_distance": float(distances[local_spot]),
        }

        if candidate_counts.get(local_spot, 0) > 1:
            print(
                "WARNING: multiple coordinate-file candidates within tolerance: "
                f"phase={phase}, local_spot={local_spot}",
                file=sys.stderr,
            )

    return geometry


# ============================================================
# READ PHASE DATA + GEOMETRIES
# ============================================================

datasets = find_dataset_csvs()

# All phases belonging to the same analysis must have the same fixed value.
# Example: A1 + T must consistently correspond to A1_T=20 in every phase.
fixed_values = {d["fixed_value"] for d in datasets}
if len(fixed_values) != 1:
    details = "\n  ".join(
        f"{d['phase']}: {sensor}_{constant}={d['fixed_value']}"
        for d in datasets
    )
    raise RuntimeError(
        f"Inconsistent fixed {constant} values across phases:\n  {details}"
    )

fixed_value = datasets[0]["fixed_value"]
outdir = merged_root / f"{sensor}_{constant}={fixed_value}"
outdir.mkdir(parents=True, exist_ok=True)

print(f"Found {len(datasets)} phase datasets:")
for d in datasets:
    print(f"  {d['phase']}: {d['path']}")
print(f"Phase-3 output directory: {outdir}")

# Remove stale phase-3 products for this sensor/condition.
for pattern in (
    f"{sensor}_{constant}=*_global_ID.csv",
    f"{sensor}_{constant}=*_global_complete.csv",
):
    for stale in outdir.glob(pattern):
        stale.unlink()

for suffix in (
    "all_phases_global_ID.csv",
    "hotspot_presence.csv",
    "phase_changes.csv",
    "global_catalog.csv",
    "global_mapping.csv",
    "geometry_plan.csv",
):
    stale = outdir / f"{sensor}_{constant}_{suffix}"
    if stale.exists():
        stale.unlink()

for d in datasets:
    df = pd.read_csv(d["path"])
    check_columns(df, d["path"])

    for col in ("x", "y", "T", "v"):
        df[col] = pd.to_numeric(df[col], errors="raise")
    if "v_fin" in df.columns:
        df["v_fin"] = pd.to_numeric(df["v_fin"], errors="coerce")

    d["df"] = df
    d["local_spots"] = mean_coordinates_per_local_spot(df)
    d["coordinates"] = read_reference_coordinates(d["coord_path"])
    d["local_geometry"] = attach_local_geometry(
        d["local_spots"], d["coordinates"], d["phase"]
    )


# ============================================================
# GLOBAL-ID CATALOG
# ============================================================

reference = datasets[0]
ref_local = reference["local_spots"].sort_values("spot").reset_index(drop=True)

catalog_rows = []
reference_mapping = {}

for gid, row in enumerate(ref_local.itertuples(index=False)):
    local_spot = row.spot
    reference_mapping[local_spot] = gid
    geom = reference["local_geometry"][local_spot]
    catalog_rows.append({
        "spot": gid,
        "x_ref": geom["x"],
        "y_ref": geom["y"],
        "first_seen_phase": reference["phase"],
        "first_seen_run": reference["run_number"],
        "first_seen_order": reference["phase_order"],
    })

catalog = pd.DataFrame(catalog_rows)
next_global_id = len(catalog_rows)

matched_datasets = []
mapping_rows = []

for d in datasets:
    phase = d["phase"]
    run_number = d["run_number"]
    local_spots = d["local_spots"]

    if phase == "before_annealing":
        mapping = dict(reference_mapping)
        distances = {local_spot: 0.0 for local_spot in mapping}
        candidate_counts = {local_spot: 1 for local_spot in mapping}
        match_types = {local_spot: "reference" for local_spot in mapping}
    else:
        mapping, distances, candidate_counts = greedy_one_to_one(
            source_rows=local_spots,
            target_rows=catalog,
            source_id="spot",
            target_id="spot",
            sx="x_mean",
            sy="y_mean",
            tx="x_ref",
            ty="y_ref",
            radius=match_radius,
        )
        match_types = {local_spot: "matched" for local_spot in mapping}

        for row in local_spots.itertuples(index=False):
            local_spot = row.spot
            if local_spot in mapping:
                continue

            gid = next_global_id
            next_global_id += 1
            geom = d["local_geometry"][local_spot]

            mapping[local_spot] = gid
            distances[local_spot] = np.nan
            match_types[local_spot] = "new"

            catalog = pd.concat([
                catalog,
                pd.DataFrame([{
                    "spot": gid,
                    "x_ref": geom["x"],
                    "y_ref": geom["y"],
                    "first_seen_phase": phase,
                    "first_seen_run": run_number,
                    "first_seen_order": d["phase_order"],
                }]),
            ], ignore_index=True)

            print(
                "NEW HOTSPOT: "
                f"phase={phase}, local_spot={local_spot}, global_spot={gid}, "
                f"x={geom['x']:.3f}, y={geom['y']:.3f}"
            )

    local_lookup = local_spots.set_index("spot")
    catalog_lookup = catalog.set_index("spot")

    for local_spot, gid in mapping.items():
        loc = local_lookup.loc[local_spot]
        ref = catalog_lookup.loc[gid]
        geom = d["local_geometry"][local_spot]
        n_candidates = int(candidate_counts.get(local_spot, 0))

        mapping_rows.append({
            "phase": phase,
            "phase_order": d["phase_order"],
            "run_number": run_number,
            "local_spot": local_spot,
            "spot": int(gid),
            "x_mean": float(loc["x_mean"]),
            "y_mean": float(loc["y_mean"]),
            "x": geom["x"],
            "y": geom["y"],
            "integration_area": geom["integration_area"],
            "integration_radius": geom["integration_radius"],
            "x_ref": float(ref["x_ref"]),
            "y_ref": float(ref["y_ref"]),
            "match_distance": distances.get(local_spot, np.nan),
            "match_type": match_types[local_spot],
            "candidate_count": n_candidates,
        })

        if n_candidates > 1:
            print(
                "WARNING: ambiguous global spatial neighbourhood: "
                f"phase={phase}, local_spot={local_spot}, "
                f"candidate_count={n_candidates}. Closest available match used.",
                file=sys.stderr,
            )

    # Keep the old detection-only per-phase global-ID file for compatibility.
    df_global = d["df"].copy()
    df_global["spot"] = df_global["spot"].map(mapping)
    if df_global["spot"].isna().any():
        raise RuntimeError(f"Internal error: unmapped spots remain in phase {phase}.")
    df_global["spot"] = df_global["spot"].astype(int)
    sort_cols = ["spot", "v" if constant == "T" else "T"]
    df_global = df_global.sort_values(sort_cols, kind="stable").reset_index(drop=True)
    detection_only_output = outdir / f"{d['path'].stem}_global_ID.csv"
    df_global.to_csv(detection_only_output, index=False)

    matched_datasets.append({
        **d,
        "mapping": mapping,
        "distances": distances,
        "df_global": df_global,
        "present_spots": set(df_global["spot"].astype(int).unique()),
    })

mapping_df = pd.DataFrame(mapping_rows)
all_global_spots = sorted(catalog["spot"].astype(int).unique())


# ============================================================
# PRESENCE / TEMPORAL STATUS BASED ONLY ON SOURCE DETECTION
# ============================================================

first_seen_order = {
    int(row.spot): int(row.first_seen_order)
    for row in catalog.itertuples(index=False)
}

presence_rows = []

for phase_index, d in enumerate(matched_datasets):
    present = d["present_spots"]
    previous_present = (
        matched_datasets[phase_index - 1]["present_spots"]
        if phase_index > 0 else set()
    )
    inverse_mapping = {int(gid): local for local, gid in d["mapping"].items()}

    for gid in all_global_spots:
        detected = gid in present
        first_idx = first_seen_order[gid]

        if phase_index < first_idx:
            status = "not_yet_detected"
        elif phase_index == first_idx:
            status = "reference" if phase_index == 0 else "appeared"
        else:
            was_detected_previous = gid in previous_present
            if detected and was_detected_previous:
                status = "present"
            elif detected and not was_detected_previous:
                status = "reappeared"
            elif not detected and was_detected_previous:
                status = "disappeared"
            else:
                status = "absent"

        local_spot = inverse_mapping.get(gid, np.nan)
        presence_rows.append({
            "spot": gid,
            "phase": d["phase"],
            "phase_order": phase_index,
            "run_number": d["run_number"],
            "detection": "present" if detected else "absent",
            "detected": bool(detected),
            "status": status,
            "local_spot": local_spot,
        })

presence = pd.DataFrame(presence_rows)


# ============================================================
# GEOMETRY PROPAGATION + FIXED INTEGRATION RADIUS
# ============================================================
# Policy:
#   COORDINATES:
#     - detected in target phase -> use that phase's own x,y;
#     - absent after it has been seen -> use the most recent previous detection;
#     - absent before first appearance -> use the first future detection.
#
#   INTEGRATION RADIUS:
#     - inspect ONLY the phases in which the global hotspot is genuinely
#       detected;
#     - choose ONCE the largest measured integration radius among those
#       detections;
#     - keep exactly that radius (and the integration area associated with
#       the same detection) for EVERY phase, including forced measurements
#       before the first detection and after a disappearance.
#
# This prevents the luminosity evolution from being biased by a changing
# integration aperture and, by using the largest detected aperture, avoids
# clipping a hotspot in phases where its detected extent is larger. The
# hotspot centre may still follow measured phase-to-phase coordinate changes.

geometry_rows = []

for gid in all_global_spots:
    detections = mapping_df[mapping_df["spot"] == gid].sort_values("phase_order")
    if detections.empty:
        raise RuntimeError(f"Global hotspot {gid} has no detected geometry.")

    # Canonical aperture: largest radius among ALL REAL DETECTIONS of this
    # global hotspot.  The corresponding integration area is taken from the
    # same detection so that radius and area remain internally consistent.
    max_radius_idx = detections["integration_radius"].astype(float).idxmax()
    max_radius_detection = detections.loc[max_radius_idx]

    fixed_integration_radius = float(max_radius_detection["integration_radius"])
    fixed_integration_area = float(max_radius_detection["integration_area"])
    fixed_radius_source_phase = max_radius_detection["phase"]
    fixed_radius_source_run = max_radius_detection["run_number"]

    for d in matched_datasets:
        target_order = d["phase_order"]
        own = detections[detections["phase_order"] == target_order]

        if not own.empty:
            coordinate_source = own.iloc[0]
            geometry_mode = "phase_detection"
        else:
            previous = detections[detections["phase_order"] < target_order]
            if not previous.empty:
                coordinate_source = previous.iloc[-1]
                geometry_mode = "previous_detection"
            else:
                future = detections[detections["phase_order"] > target_order]
                if future.empty:
                    raise RuntimeError(
                        f"No usable geometry found for global hotspot {gid}, "
                        f"target phase {d['phase']}."
                    )
                coordinate_source = future.iloc[0]
                geometry_mode = "first_future_detection"

        p = presence[
            (presence["spot"] == gid) &
            (presence["phase_order"] == target_order)
        ].iloc[0]

        geometry_rows.append({
            "spot": gid,
            "phase": d["phase"],
            "phase_order": target_order,
            "run_number": d["run_number"],
            "detection": p["detection"],
            "status": p["status"],
            # x,y may follow the measured centre when the hotspot is detected.
            "x": float(coordinate_source["x"]),
            "y": float(coordinate_source["y"]),
            # The aperture is fixed to the maximum radius observed across
            # the phases where this hotspot is genuinely detected.
            "integration_area": fixed_integration_area,
            "integration_radius": fixed_integration_radius,
            "geometry_source_phase": coordinate_source["phase"],
            "geometry_source_run": coordinate_source["run_number"],
            "geometry_mode": geometry_mode,
            "integration_radius_source_phase": fixed_radius_source_phase,
            "integration_radius_source_run": fixed_radius_source_run,
            # Distance used when the COORDINATE source detection was assigned
            # to its global hotspot ID. The aperture itself is fixed from the
            # maximum-radius real detection and is independent of this distance.
            "match_distance": coordinate_source["match_distance"],
        })

geometry_plan = pd.DataFrame(geometry_rows)
geometry_plan = geometry_plan.sort_values(
    ["spot", "phase_order"], kind="stable"
).reset_index(drop=True)

geometry_plan_output = outdir / f"{sensor}_{constant}_geometry_plan.csv"
geometry_plan.drop(columns=["phase_order"]).to_csv(
    geometry_plan_output, index=False
)
print(f"Created: {geometry_plan_output}")


# ============================================================
# RUN ROOT ON COMPLETE GLOBAL COORDINATES FOR EVERY PHASE
# ============================================================

def write_complete_coordinate_file(d, phase_plan: pd.DataFrame) -> Path:
    coord_output = d["run_dir"] / "4coordinates" / (
        f"{d['run_prefix']}_{d['phase']}_run={d['run_number']}_"
        "global_complete_coordinates.txt"
    )

    ordered = phase_plan.sort_values("spot")
    with coord_output.open("w", encoding="utf-8") as handle:
        for row in ordered.itertuples(index=False):
            handle.write(
                f"{row.x:.6f}, {row.y:.6f}, "
                f"{row.integration_area:.6f}, {row.integration_radius:.6f}\n"
            )

    return coord_output


def map_root_results_to_plan(result_df: pd.DataFrame, phase_plan: pd.DataFrame,
                             root_file: Path) -> pd.DataFrame:
    needed = ["x", "y", "luminosity", "error"]
    missing = [c for c in needed if c not in result_df.columns]
    if missing:
        raise RuntimeError(
            f"ROOT output for {root_file} is missing columns {missing}. "
            f"Found: {list(result_df.columns)}"
        )

    result = result_df.copy()
    result["x"] = pd.to_numeric(result["x"], errors="raise")
    result["y"] = pd.to_numeric(result["y"], errors="raise")
    result["luminosity"] = pd.to_numeric(result["luminosity"], errors="raise")
    result["error"] = pd.to_numeric(result["error"], errors="raise")
    result["result_index"] = np.arange(len(result), dtype=int)

    plan = phase_plan.copy().reset_index(drop=True)
    plan["plan_index"] = np.arange(len(plan), dtype=int)

    if len(result) != len(plan):
        raise RuntimeError(
            f"ROOT returned {len(result)} luminosity rows for {root_file}, "
            f"but {len(plan)} global coordinates were supplied."
        )

    mapping, distances, _ = greedy_one_to_one(
        source_rows=result,
        target_rows=plan,
        source_id="result_index",
        target_id="plan_index",
        sx="x", sy="y", tx="x", ty="y",
        radius=coord_match_radius,
    )

    if len(mapping) != len(result):
        raise RuntimeError(
            f"Could not map every ROOT luminosity result back to the global "
            f"coordinate plan for {root_file}."
        )

    plan_lookup = plan.set_index("plan_index")
    records = []
    for result_row in result.itertuples(index=False):
        plan_index = mapping[result_row.result_index]
        p = plan_lookup.loc[plan_index]
        records.append({
            "spot": int(p["spot"]),
            # Use exactly the geometry supplied for the integration.
            "x": float(p["x"]),
            "y": float(p["y"]),
            "luminosity": float(result_row.luminosity),
            "error": float(result_row.error),
            "integration_area": float(p["integration_area"]),
            "integration_radius": float(p["integration_radius"]),
            "phase": p["phase"],
            "run_number": p["run_number"],
            "detection": p["detection"],
            "status": p["status"],
            "geometry_source_phase": p["geometry_source_phase"],
            "geometry_source_run": p["geometry_source_run"],
            "geometry_mode": p["geometry_mode"],
            "integration_radius_source_phase": p["integration_radius_source_phase"],
            "integration_radius_source_run": p["integration_radius_source_run"],
            # This is the spatial distance used for the GLOBAL-ID assignment,
            # not the internal ROOT-result -> coordinate-plan matching distance.
            "match_distance": p["match_distance"],
        })

    return pd.DataFrame(records)


complete_phase_frames = []

for d in matched_datasets:
    phase_plan = geometry_plan[
        geometry_plan["phase_order"] == d["phase_order"]
    ].copy()
    coord_file = write_complete_coordinate_file(d, phase_plan)

    print(
        f"Forced-measurement phase {d['phase']}: "
        f"{len(phase_plan)} global hotspots, {len(d['root_files'])} TH2F files"
    )

    phase_measurements = []

    for root_file in d["root_files"]:
        t_value = extract_parameter_from_name(root_file.name, "T")
        v_value = extract_parameter_from_name(root_file.name, "v")

        result_csv = spot_lum_dir / "luminosity_results.csv"
        if result_csv.exists():
            result_csv.unlink()

        macro_call = (
            f'{spot_lum_macro}("{root_file}","{coord_file}")'
        )

        completed = subprocess.run(
            ["root", "-l", "-q", macro_call],
            cwd=spot_lum_dir,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )

        if completed.returncode != 0:
            print(completed.stdout, file=sys.stderr)
            raise RuntimeError(
                f"ROOT luminosity macro failed for {root_file} "
                f"with exit code {completed.returncode}."
            )

        if not result_csv.is_file():
            print(completed.stdout, file=sys.stderr)
            raise RuntimeError(
                f"ROOT did not create luminosity_results.csv for {root_file}."
            )

        raw_result = pd.read_csv(result_csv)
        result_csv.unlink()

        measured = map_root_results_to_plan(raw_result, phase_plan, root_file)
        measured["T"] = t_value
        measured["v"] = v_value

        if constant == "T":
            measured["v_fin"] = (
                v_value - float(vbd_text) if vbd_text else np.nan
            )

        phase_measurements.append(measured)

    phase_complete = pd.concat(phase_measurements, ignore_index=True)
    varying_column = "v" if constant == "T" else "T"
    phase_complete = phase_complete.sort_values(
        ["spot", varying_column], kind="stable"
    ).reset_index(drop=True)

    preferred = ["spot", "x", "y", "luminosity", "error", "T", "v"]
    if "v_fin" in phase_complete.columns:
        preferred.append("v_fin")
    preferred += [
        "phase", "detection", "status",
        "integration_radius", "integration_area",
        "geometry_source_phase", "geometry_source_run", "geometry_mode",
        "integration_radius_source_phase", "integration_radius_source_run",
        "run_number", "match_distance",
    ]
    phase_complete = phase_complete[preferred]

    phase_output = outdir / f"{d['path'].stem}_global_complete.csv"
    phase_complete.to_csv(phase_output, index=False)
    print(f"Created: {phase_output}")

    phase_complete["__phase_order"] = d["phase_order"]
    complete_phase_frames.append(phase_complete)


# ============================================================
# FINAL COMPLETE MASTER FILE
# ============================================================

master = pd.concat(complete_phase_frames, ignore_index=True, sort=False)
varying_column = "v" if constant == "T" else "T"
master = master.sort_values(
    ["spot", "__phase_order", varying_column], kind="stable"
).reset_index(drop=True)
master = master.drop(columns=["__phase_order"])

master_output = outdir / f"{sensor}_{constant}_all_phases_global_ID.csv"
master.to_csv(master_output, index=False)
print(f"Created: {master_output}")


# ============================================================
# PRESENCE / CHANGE / CATALOG DIAGNOSTICS
# ============================================================

presence_output = outdir / f"{sensor}_{constant}_hotspot_presence.csv"
presence_to_save = presence.drop(columns=["phase_order"])
presence_to_save.to_csv(presence_output, index=False)
print(f"Created: {presence_output}")

phase_change_rows = []
for d in matched_datasets:
    pp = presence[presence["phase"] == d["phase"]]
    counts = pp["status"].value_counts()
    phase_change_rows.append({
        "phase": d["phase"],
        "run_number": d["run_number"],
        "n_detected": int(pp["detected"].sum()),
        "n_reference": int(counts.get("reference", 0)),
        "n_appeared": int(counts.get("appeared", 0)),
        "n_reappeared": int(counts.get("reappeared", 0)),
        "n_disappeared": int(counts.get("disappeared", 0)),
        "n_absent": int(counts.get("absent", 0)),
        "n_not_yet_detected": int(counts.get("not_yet_detected", 0)),
    })

phase_changes = pd.DataFrame(phase_change_rows)
phase_changes_output = outdir / f"{sensor}_{constant}_phase_changes.csv"
phase_changes.to_csv(phase_changes_output, index=False)
print(f"Created: {phase_changes_output}")

last_seen_phase = {}
last_seen_run = {}
for gid in all_global_spots:
    seen = presence[(presence["spot"] == gid) & (presence["detected"])]
    last = seen.iloc[-1]
    last_seen_phase[gid] = last["phase"]
    last_seen_run[gid] = last["run_number"]

catalog["last_seen_phase"] = catalog["spot"].map(last_seen_phase)
catalog["last_seen_run"] = catalog["spot"].map(last_seen_run)
catalog = catalog.drop(columns=["first_seen_order"])
catalog = catalog.sort_values("spot").reset_index(drop=True)

catalog_output = outdir / f"{sensor}_{constant}_global_catalog.csv"
catalog.to_csv(catalog_output, index=False)
print(f"Created: {catalog_output}")

mapping_output = outdir / f"{sensor}_{constant}_global_mapping.csv"
mapping_df.drop(columns=["phase_order"]).sort_values(
    ["spot", "phase"], kind="stable"
).to_csv(mapping_output, index=False)
print(f"Created: {mapping_output}")


# ============================================================
# FINAL REPORT
# ============================================================

print("")
print("============================================")
print("PHASE 3 COMPLETED")
print(f"Global hotspots: {len(all_global_spots)}")
print("")

for row in phase_changes.itertuples(index=False):
    print(
        f"{row.phase}: detected={row.n_detected}, "
        f"appeared={row.n_appeared}, reappeared={row.n_reappeared}, "
        f"disappeared={row.n_disappeared}"
    )

print("")
print("For every hotspot, luminosity and error were measured from TH2F using")
print("an integration radius fixed from its FIRST real detection and kept constant")
print("across all phases. Absent hotspots were still measured at propagated coordinates.")
print(f"Master file:    {master_output}")
print(f"Geometry plan:  {geometry_plan_output}")
print(f"Presence file:  {presence_output}")
print(f"Change report:  {phase_changes_output}")
print("============================================")
PY_PHASE3
}

# ------------------------------------------------------------
# MAIN
# ------------------------------------------------------------

main() {
    check_requirements

    printf '\n'
    printf '============================================================\n'
    printf 'AUTOMATED EMMI ANALYSIS\n'
    printf 'BASE_DIR:  %s\n' "$BASE_DIR"
    printf 'DATA_DIR:  %s\n' "$DATA_DIR"
    printf 'SENSOR:    %s\n' "$SENSOR"
    printf 'CONSTANT:  %s\n' "$CONSTANT"
    printf '============================================================\n'

    if [[ "$CONSTANT" == "T" ]]; then
        local vbd
        vbd="$(get_vbd)"

        if [[ -n "$vbd" ]]; then
            printf 'Configured VBD for %s: %s V\n' "$SENSOR" "$vbd"
        else
            warn "VBD for $SENSOR is not configured; v_fin will be NaN."
        fi
    fi

    # ---------------- PHASE 1 ----------------
    process_before_annealing

    # ---------------- PHASE 2 ----------------
    process_annealing_phases

    # ---------------- PHASE 3 ----------------
    merge_all_phases_global_ids

    printf '\n'
    printf '============================================================\n'
    printf 'PHASES 1, 2 AND 3 COMPLETED SUCCESSFULLY\n'
    printf 'Sensor:   %s\n' "$SENSOR"
    printf 'Constant: %s\n' "$CONSTANT"
    printf 'Alignment metadata: %s\n' "$ALIGNMENT_TABLE"
    printf 'Merged files:       %s\n' "$MERGED_DIR"
    printf '============================================================\n'
}

main "$@"
